### ISSUE TITLE
Replace Service by source generator?

### ISSUE THREAD

**Issue by bernardnormier** [icerpc/icerpc-csharp#2663]
Service is a fairly simple class that essentially generates the implementation of `IDispatcher.DispatchAsync` at runtime, using reflection.

I am wondering if we could replace it by a source generator (see for example https://andrewlock.net/creating-a-source-generator-part-1-creating-an-incremental-source-generator/) that actually generates this DispatchAsync method.

Current code:
```
internal class Hello : Service, IHello { ... }
```

With source generator:
```
[Service]
internal partial class Hello : IHello { ... }
```

where this `[Service]` would generate:
```
internal partial class Hello : IDispatcher
{
  public virtual ValueTask<OutgoingRequest> DispatchAsync(IncomingRequest request, CancellationToken cancellationToken)
  {
     ...
  }
}
```

The advantage is `Hello` wouldn't derive from any class. This allows the application to pick another base class.

We'd need to be careful with inheritance. E.g. It should be possible for DerivedHello to derive from Hello:
```
[Service]
internal partial class DerivedHello : Hello, IDerivedHello { ... } // reuses Hello for IHello
```

**Comment by pepone** [comment]
Fixed in #3692
