### ISSUE TITLE
Implemented by in C# API reference

### ISSUE THREAD

**Issue by bernardnormier** [icerpc/icerpc-csharp#3452]
In the Microsoft API reference, you can easily see what implements an interface or derives from an abstract class.

Can you do the same for our API reference?

For example:
https://docs.testing.zeroc.com/api/csharp/api/IceRpc.IInvoker.html

It would be nice to show the classes that implement IInvoker.

**Comment by pepone** [comment]
Closing as this is currently not supported with docfx
