### ISSUE TITLE
refactor the code to encode proxies as their "value.ServiceAddress"

### ISSUE THREAD

**Issue by pepone** [icerpc/icerpc-csharp#3557]
The ideal however would be to refactor the code to encode proxies as their "value.ServiceAddress" and use the regular ServiceAddress encoding (as provided by the custom ServiceAddress type). Not duplicate the custom logic.

_Originally posted by @bernardnormier in https://github.com/icerpc/icerpc-csharp/pull/3555#pullrequestreview-1539693651_

**Comment by bernardnormier** [comment]
This was fixed by #3806.
