### ISSUE TITLE
Slic and client-to-server streaming

### ISSUE THREAD

**Issue by bernardnormier** [icerpc/icerpc-csharp#3665]
I am writing a new example where a client slowly streams data to a server (a new element every 5 seconds).

After a while, the connection dies and the client Debug log shows me:
```
dbug: IceRpc.ClientConnection[7]
      Client connection from '[::1]:54372' to '[::1]:10000' failed to shutdown
      IceRpc.IceRpcException: The connection did not receive any bytes for over 30 s.
```

The only activity on this connection is this slow streaming. As I understand it, the client should receive Slic StreamWindowUpdate frames from time to time from the server, but apparently doesn't? 

Maybe we don't send these StreamWindowUpdate frames often enough in this scenario?

**Comment by bernardnormier** [comment]
I think there are 3 potential solutions here:

1) Send StreamWindowUpdate (see https://docs.icerpc.dev/icerpc/slic-transport/flow-control) more often and use it as form of ACK.

I don't find this particularly elegant: I'd rather keep flow control and keep alive separate.

2) Send Ping frames from the client more often and for two separate purposes:
 - to keep the server's idle timer from timing out (by writing a Ping to the connection) - that's what we do now
 - to keep the client's idle timer from timing out by sending a Ping to elicit a Pong (ack) from the server

We could/should include some coordination so that a completely idle connection does send two Pings at the same time.

3) Send Ping frames from the client to the server (like today, idle-timeout / 2 after the last write) and also from the server to the client.

I would pick a different interval in the server - like 3/4 idle-timeout; this way, it's less likely both client and server send Ping to each other at the same time.

**Comment by pepone** [comment]
I don't understand the core issue here. If the client is streaming an element every 5 seconds, why does the server close the connection saying it didn't receive any bytes for over 30 seconds? Has the client consumed all the send credit?

**Comment by bernardnormier** [comment]
It's the client that does not receive any byte for 30 seconds and closes (aborts) the connection.

**Comment by bentoi** [comment]
From the QUIC spec:

> Sending a packet containing a PING frame restarts the idle timeout for this endpoint also if this is the first ack-eliciting packet sent since receiving a packet. Sending a PING frame causes the peer to respond with an acknowledgment, which also restarts the idle timeout for the endpoint.

AFAICT, this matches 2. with the difference that instead of relying on a Pong frame, QUIC relies on the acknowledgment sent by the peer upon receiving the PING frame. So I would go for 2: send a PING frame to both defer the peer idle timeout and the local idle timeout.

**Comment by bernardnormier** [comment]
I also prefer 2 - I find it cleaner. With 2, the client is solely in charge of keeping the connection alive and can avoid duplicate pings.

**Comment by bernardnormier** [comment]
Should we also add a PongTimeout property to SliceTransportOptions? Meaning = how long to wait for a Pong before considering the connection dead.

This corresponds to the DisconnectTimeoutMs in msquic (https://github.com/microsoft/msquic/blob/main/docs/Settings.md).
