### ISSUE TITLE
XML comments removed / not rendered on NuGet.org

### ISSUE THREAD

**Issue by bernardnormier** [icerpc/icerpc-csharp#3680]
See https://www.nuget.org/packages/IceRpc.Slice.Tools#readme-body-tab

There are a few XML code blocks with blank lines. In the actual README.md, these are XML comments.

**Comment by externl** [comment]
Should we just remove the comments?

**Comment by bernardnormier** [comment]
The comments are helpful and it would be better to render them.

**Comment by pepone** [comment]
I think we have to XML escape them

**Comment by pepone** [comment]
XML escaping doesn't work here, tried a few things but I cannot get XML comments to render with NuGet READMEs.

I think the only option is to move this text out of the xml code block.
