### ISSUE TITLE
Add support for protobuf streaming RPCs

### ISSUE THREAD

**Issue by pepone** [icerpc/icerpc-csharp#3707]
The Protobuf generator in https://github.com/icerpc/icerpc-csharp/tree/main/tools/protobuf/IceRpc.ProtocGen only handles Unary RPCs.

We should support streaming RPCs just like we do for Slice.

**Comment by bernardnormier** [comment]
I propose to encode streams of Protobuf messages like gRPC, i.e. the payload of a Protobuf-encoded request or response is a
"repeated sequence of Length-Prefixed-Message items" where:

- Length-Prefixed-Message → Compressed-Flag Message-Length Message
- Compressed-Flag → 0 / 1 # encoded as 1 byte unsigned integer
- Message-Length → {length of Message} # encoded as 4 byte unsigned integer (big endian)
- Message → *{binary octet}

See https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md

And unary RPCs should be the same, except there is only one Protobuf message.

I would also map a stream of Protobuf messages to an `IAsyncEnumerable<T>`, like we do for Slice.

**Comment by pepone** [comment]
I understand the idea is to be able to forward gRPC messages over icerpc without re-encoding. How would an IceRPC server handle a compressed message like this?

**Comment by bernardnormier** [comment]
> How would an IceRPC server handle a compressed message like this?

The cleanest would be to leave this decompression to the IceRPC + Protobuf integration.

At the core level (IceRPC), it's just bytes. Initially, we would simply not support this gRPC-style compression in IceRPC + Protobuf.
