### ISSUE TITLE
Tools layout

### ISSUE THREAD

**Issue by pepone** [icerpc/icerpc-csharp#3709]
The current layout for tools is not great

```
tools/IceRpc.Slice.Tools
tools/protobuf/Common
tools/protobuf/IceRpc.Protobuf.Tools
tools/protobuf/IceRpc.ProtocGen
tools/slicec-cs
```

I think it would make more sense to move the Slice-related tools into a new `slice` subdirectory.

```
tools/protobuf/Common
tools/protobuf/IceRpc.Protobuf.Tools
tools/protobuf/IceRpc.ProtocGen
tools/slice/slicec-cs
tools/slice/IceRpc.Slice.Tools
```

**Comment by InsertCreativityHere** [comment]
I agree, that seems more logical now that it's split between protobuf and slice.

**Comment by pepone** [comment]
@bernardnormier suggested moving everything to the tools top-level:

 ```
tools/Common
tools/IceRpc.Protobuf.Tools
tools/IceRpc.ProtocGen
tools/slicec-cs
tools/IceRpc.Slice.Tools
```

And we will have a single `IceRpc.Tools.sln` for the C# projects
