### ISSUE TITLE
Need  README.md for IceRPC Protobuf tools

### ISSUE THREAD

**Issue by bernardnormier** [icerpc/icerpc-csharp#3711]
The NuGet correctly packages the top-level README by mistake.

**Comment by pepone** [comment]
I added a placeholder README that gets included in the package.

The README should mention that this package bundles the Protobuf files and protoc compilers from Google.Protobuf.Tools

**Comment by pepone** [comment]
Fixed in 82a5fd662bb756d93b6766e4b7431c00584f3eb2
