### ISSUE TITLE
All the Protobuf tests and examples should use the standard Protobuf naming conventions

### ISSUE THREAD

**Issue by pepone** [icerpc/icerpc-csharp#3756]
> All the Protobuf tests and examples should use the standard Protobuf naming conventions. For RPC methods, it's Pascal case.

_Originally posted by @bernardnormier in https://github.com/icerpc/icerpc-csharp/pull/3753#discussion_r1394439715_

**Comment by bernardnormier** [comment]
There are still a number of bugs. For example:
```
package IceRpc.Protobuf.Tests;
```

is not a normal Protobuf package name,
