### ISSUE TITLE
Implement option deprecated = true

### ISSUE THREAD

**Issue by bernardnormier** [icerpc/icerpc-csharp#3784]
It would be nice to implement this option for both services and rpc methods. Currently we just ignore it.

**Comment by pepone** [comment]
This seems to work for method descriptors:

```
        if (method.GetOptions()?.Deprecated ?? false)
        {
            methods += @$"
[global::System.Obsolete]".Trim();
        }
```

This doesn't seem to work for the service descriptor:

```
if (service.GetOptions()?.Deprecated ?? false)
{
    clientInterface += "[global::System.Obsolete]";
}
```

For the service deprecation I'm using 

```
service MyDeprecatedOperations {
    option deprecated = true;
    rpc DeprecatedOp(google.protobuf.Empty) returns (google.protobuf.Empty);
}
```

**Comment by pepone** [comment]
> This doesn't seem to work for the service descriptor:

There was a missing new line and the `[global::System.Obsolete]` was added in the comment above.
