### ISSUE TITLE
Allow cs::identifier on custom

### ISSUE THREAD

**Issue by bernardnormier** [icerpc/icerpc-csharp#3805]
It would be helpful to support `cs::identifier` on custom.

The mapped identifier is used to lookup the encode and decode methods, and occasionally you want to customize this identifier.

Use case:
```slice
[cs::identifier("IceObject")]
interface Object {
   ...
}

/// The ObjectProxy data type, encoded as a service address.
[cs::type("IceRpc.Slice.Ice.IceObjectProxy")]
custom ObjectProxy
```
In this case, it would be preferable to have C# encode/decode methods with the "IceObjectProxy" name, as opposed to the default (ObjectProxy).

**Comment by InsertCreativityHere** [comment]
This was implemented by #3807.
