### ISSUE TITLE
icerpc-csharp/slice files updated by #3806 and #3808

### ISSUE THREAD

**Issue by bernardnormier** [icerpc/icerpc-csharp#3847]
The icerpc-csharp/slice subtree was updated directly by PRs #3806 and #3808 (my PRs), when the correct procedure is to update the files in icerpc-slice first.

**Comment by pepone** [comment]
Updated the subtree by executing

```
git subtree push --prefix=slice git@github.com:icerpc/icerpc-slice.git main
```

From `icerpc-csharp`
