### ISSUE TITLE
The Unknown enumerator should extend the base enumeration

### ISSUE THREAD

**Issue by pepone** [icerpc/icerpc-csharp#3869]
For an unchecked enum with fields we generate something like

```
[Dunet.Union]
public abstract partial record class Shape
{
    ....
    public partial record class Triangle(uint Side1, uint Side2, uint Side3) : Shape {...}
    public partial record class Unknown {...}
}

public static class ShapeSliceDecoderExtensions
{
    public static Shape DecodeShape(this ref SliceDecoder decoder)
    {
        return decoder.DecodeVarInt32() switch
        {
            ....
            int value => new Shape.Unknown(value, decoder.DecodeSequence<byte>())
        };
}
```

When I saw this generated code, I was wondering how can it work, `Decode` returns an `Unknown` which doesn't extend `Shape`. The answer is that Dunet generates another partial that adds `Unknown : Shape`.

While this works, I think it would be clear if we do the same for all the enumerators, either always explicitly extend the parent record, or always rely on the Dunet generator to add this in the generated partial.

**Comment by bernardnormier** [comment]
We should generate `: <base>` for enum for clarity. It's just an oversight.
