### ISSUE TITLE
Include arm64 protoc with our IceRpc.Protobuf.Tools

### ISSUE THREAD

**Issue by pepone** [icerpc/icerpc-csharp#3966]
For macOS you can use Rosseta, but as @ReeceHumphreys found out if you are using a dev container on macOS, the provided Linux image is arm64 and the `protoc` compiler is not available.

The `IceRpc.Protobuf.Tools` NuGet package repackages the `protoc` binaries from the `Google.Protobuf.Tools` NuGet package; however, it lacks arm64 binaries.

We can upgrade the `IceRpc.Protobuf.Tools` NuGet package to download the binaries from the `Google.Protobuf.Tools` release page: https://github.com/protocolbuffers/protobuf/releases

**Comment by bernardnormier** [comment]
Once this done, please remember to remove "2" in the Prerequesites:
https://github.com/icerpc/icerpc-csharp/blob/main/BUILDING.md#prerequisites

**Comment by bernardnormier** [comment]
Also update the bottom of https://github.com/icerpc/icerpc-csharp/blob/main/tools/IceRpc.Protobuf.Tools/README.md

**Comment by ReeceHumphreys** [comment]
Closed by #3969
