### ISSUE TITLE
Detecting when an outgoing request is sent

### ISSUE THREAD

**Issue by bernardnormier** [icerpc/icerpc-csharp#4001]
When we send a one-way request, the invocation completes when the outgoing request is sent. For example:

```csharp
await logger.LogAsync(message); // log operation is oneway
// the message was sent. Don't know if it was received
```

Then, when we send a two-way request, there is no easy way to find out when the request is sent.
```csharp
Task<string> task = greeter.GreetAsync(name);
string greeting = await task; // we know it was sent because we received the response
```

Knowing when a (two-way) request is sent is useful for flow-control. If the peer stops reading (applies back pressure), it's desirable to find out, with one-way request and also with two-way requests.

Currently, we can figure this out by decorating the OutgoingRequest's payload PipeReader. When IceRPC calls Complete on this payload, it means the request was sent or the sending failed (let's ignore payload continuations for now)

icerpc protocol:
https://github.com/icerpc/icerpc-csharp/blob/4946120c56c50285e6499c6f458e6f5131ef0656/src/IceRpc/Internal/IceRpcProtocolConnection.cs#L452

ice protocol:
https://github.com/icerpc/icerpc-csharp/blob/4946120c56c50285e6499c6f458e6f5131ef0656/src/IceRpc/Internal/IceProtocolConnection.cs#L381

This PipeReader decoration is doable but not convenient. And Ice provides a much simpler API to figure out when a request is sent.

## Proposal

Add a new feature, `IRequestSentFeature`, that allows the caller to figure out when the request is sent / the sending fails:

```csharp
public interface IRequestSentFeature
{
    // Called by the protocol connection implementation when the request is sent / failed to send.
    void Sent(); 
    void SendFailed(Exception exception);
    void SendCanceled();
}

public class RequestSentFeature : IRequestSentFeature
{
    public RequestSentFeature(TaskCompletionSource tcs) { ... }

    // trivial implementation using tcs.
}
```

"request sent successfully" includes the sending of the payload continuation when there is one. 

### Usage:

```csharp
var tcs = new TaskCompletionSource();
var features = new FeatureConnection();
features.Set<IRequestSentFeature>(new RequestSentFeature(tcs));

Task<string> task = greeter.GreetAsync(name, features);
await tcs.Task;
// request was sent successfully
string greeting = await task;
```

**Comment by bernardnormier** [comment]
One difficulty is the interaction with the Retry interceptor. With the Retry interceptor, it's possible for a request to be sent multiple times.

**Comment by pepone** [comment]
Maybe we can model this around `IProgress<T>` with a progress feature that reports the state changes. 

`Sending -> Sent -> Retrying -> Sent -> Completed`

**Comment by bernardnormier** [comment]
We could keep the simple IRequestSentFeature/RequestSentFeature as I proposed it. If your request is sent multiple times by the retry interceptor, you'll see only the first send.

This is simple and useful for flow control. Retries shouldn't be very common. You want to know if the (first) sends take a long time because the peer is not reading.

Then, we should add a separate feature that gives you more insights into retries, an IRetryFeature. I would put it in the core and it would be (should be) called by any retry interceptor, including the built-in retry interceptor. Something like:

```csharp
public interceptor IRetryFeature
{
    void NewAttempt(int attempt, int maxAttempts, string? reason); // can be 1, 1, null for a non-retryable invocation
    void Sent(int attempt);
    void SendFailed(int attempt, Exception exception);
    void SendCanceled(int attempt);
}
```

However, I don't see an obvious default implementation for IRetryFeature. We could defer this retry feature until we understand better how it would be used.

**Comment by bernardnormier** [comment]
Closing because the proposal is not good.

When the server applies back pressure, it is desirable for the client to detect this back pressure _in some cases_. In many cases, the client doesn't send a large number of concurrent two-way requests - so this doesn't matter.

Setting up a feature with each invocation allows the client to build a solution, but it's a rather inconvenient solution. A more convenient solution is to install an interceptor that throws an exception when there are too many pending requests (where pending = submitted but not sent):
```csharp
for(int i = 0; i < count; ++i)
{
    bool tryAgain = false;
    do 
    {
          try
          {
               Task<string> task = greeter.GreetAsync($"{name}-{i}"); // no special feature
               taskList.Add(task);
               tryAgain = false;
          }
          catch (BackPressureException) // thrown by interceptor
          {
              await Task.Delay(backPressureDelay);
              tryAgain = true; 
          }
    } 
    while (tryAgain);
}
```

Alternatively, the client could use semaphore to know when it can send a request without exceeding the back pressure limit:

```csharp
// an interceptor releases 'semaphore' when a request is sent

await semaphore.WaitAsync(token); // can safely send this request
Task<string> task = greeter.GreetAsync($"{name}-{i}"); // no special feature
```

So, it's a matter of writing an interceptor that provides the most convenient API for a specific client application. This interceptor can use the existing hook provided by the IceRPC code, namely the completion of the Payload and Payload continuation: the IceRPC core (IceRpcProtocolConnection and IceProtocolConnection) completes the Payload (resp. PayloadContinuation) as soon as they are sent, and an interceptor can easily decorate the Payload/PayloadContinuation to detect this event.

It would be helpful to write a BackPressure example with such an interceptor.
