### ISSUE TITLE
Investigate XML formatting quirks.

### ISSUE THREAD

**Issue by ReeceHumphreys** [icerpc/icerpc-csharp#4012]
It looks like the XML formatting that was done in #4007 resulted in a few formatting quirks in some files. For example, [here]( https://github.com/icerpc/icerpc-csharp/blob/e0757db59d0dacb7b4630aa7966bb71b75ba54b3/tools/IceRpc.Slice.Tools/IceRpc.Slice.Tools.targets#L35-L37) looks a bit odd. I'm not sure if this is a misconfiguration of the formatter with prettier or if this is just a tiny quick/bug with the formatter.

**Comment by bernardnormier** [comment]
> a few formatting quirks in some files

From the only example given, it sounds like an issue with indentation within XML comments.

**Comment by bernardnormier** [comment]
As far as I can tell, this bug is not valid. prettier's xml plugin does not change the formatting of XML comments, at least not with our current configuration (see .prettierrc). We just need to fix any odd XML comment formatting by hand.
