### ISSUE TITLE
Improve mapping for classes and exceptions with required properties

### ISSUE THREAD

**Issue by bernardnormier** [icerpc/icerpc-csharp#4014]
The C# mapping for a simple class Person:
```slice
class Person {
    name: string
    age: int32
    tag(1) phoneNumber: string?
}
```

is currently:

```csharp
public partial class Person : SliceClass
{
    public string Name { get; set; }

    public int Age { get; set; }

    public string? PhoneNumber { get; set; }

    /// <summary>Constructs a new instance of <see cref="Person" />.</summary>
    public Person(
        string name,
        int age,
        string? phoneNumber)
    {
        this.Name = name;
        this.Age = age;
        this.PhoneNumber = phoneNumber;
    }

    /// <summary>Constructs a new instance of <see cref="Person" />.</summary>
    public Person(
        string name,
        int age)
    {
        this.Name = name;
        this.Age = age;
    }

    /// <summary>Constructs a new instance of <see cref="Person"/> for the Slice decoder.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public Person()
    {
        this.Name = default!;
    }

    // encode/decode logic
}
```

We provide:
 - a primary constructor to initialize all properties (including nullable properties and value types that have a reasonable default)
 - (optionally) another constructor to initialize all non-tagged properties
 - a hidden parameterless constructor used for decoding. This paramerless ctor assigns `default!` to all properties with a non-nullable reference type.

This structure is dictated in large part by the Slice1 decoding logic for classes and exceptions, where we decode the fields of the most derived slice first and then go up the inheritance chain.

## Proposal:

 - Always make the parameterless constructor public / non-hidden, with an empty body (no more `= default!`)
 - Add `required` to all properties with a non-nullable reference type
 - When there is at least one required property, add `[SetsRequiredMembers]` to the generated constructor(s) other than the parameterless constructor.

This gives users more flexibility while making the generated code cleaner.

**Comment by pepone** [comment]
> Always make the parameterless constructor public / non-hidden, with an empty body (no more = default!)

Doesn't this result in a warning about non-required required properties not being initialized?

**Comment by bernardnormier** [comment]
> Doesn't this result in a warning about non-required required properties not being initialized?

It does not, provided all properties with non-nullable reference types are marked "required".
