### ISSUE TITLE
Slice.Tools JSON error

### ISSUE THREAD

**Issue by bernardnormier** [icerpc/icerpc-csharp#4043]
I am getting this error whenever I get a redefinition error in a Slice file:

```
    /Users/bernard/builds/icerpc-csharp/tools/IceRpc.Slice.Tools/IceRpc.Slice.Tools.targets(60,5): error : Error parsing JSON: 'F' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.. JSON content: Failed: Compilation failed with 3 error(s)
```

**Comment by pepone** [comment]
This is due to the compiler emitting non JSON diagnostics:

```
{"message":"redefinition of 'Locator'","severity":"error","span":{"start":{"row":20,"col":11},"end":{"row":20,"col":18},"file":"slice\\Ice\\Locator.slice"},"notes":[{"message":"'Locator' was previously defined here","span":{"start":{"row":14,"col":11},"end":{"row":14,"col":18},"file":"slice\\Ice\\Locator.slice"}}],"error_code":"E012"}
Failed: Compilation failed with 1 error(s)
```

**Comment by externl** [comment]
It used to be (I think) that JSON output was emitted to stdout and the filed summary was sent to stderr. IIRC rust does something similar. I thought that we used to only read from stdout, or at least not emit errors if JSON unmarshaling failed.

**Comment by pepone** [comment]
No quite correct.

We used to only emit JSON to STDERR for error messages. But now with `--telemetry` we also emit telemetry info as JSON formatted data to stdout.

I guess the simple is to ignore this non JSON messages from STDOUT as we did before, and just collect the STDOUT JSON messages that has the expected telemetry data.

**Comment by InsertCreativityHere** [comment]
>  that JSON output was emitted to stdout and the filed summary was sent to stderr

It's the other way around with `slicec`, the `Compilation failed with ...` message is sent to stdout,
and all the errors are sent to stderr (either as JSON or text).

**Comment by pepone** [comment]
> Another, maybe easier fix is to change slicec-cs to emit it's telemetry to stderr instead.

Seems wrong to emit non error data to stderr

**Comment by externl** [comment]
Yeah, I'd rather just ignore non-JSON output in the tools.

**Comment by InsertCreativityHere** [comment]
Fair enough, I agree it'd be weirder, was just pitching ideas!
