### ISSUE TITLE
Rename `SourceFileCount` in `IceRpc.Protobuf.Tools`

### ISSUE THREAD

**Issue by externl** [icerpc/icerpc-csharp#4055]
I think that you're correct and "FileCount" is what we should call this,
but it looks like in `IceRpc.Protobuf.Tools`, we call this `SourceFileCount` and use `--src-file-count`:
https://github.com/icerpc/icerpc-csharp/blob/50f97c80cd47367112e037876fc41b3b08d9e200/tools/IceRpc.Protobuf.Tools/BuildTelemetryTask.cs#L19-L22
So it's a little inconsistent. Maybe after this PR, we should fix the name in the `Protobuf.Tools` to match this one,
for consistency's sake.

_Originally posted by @InsertCreativityHere in https://github.com/icerpc/telemetry/pull/4#discussion_r1755369923_

**Comment by pepone** [comment]
Fixed in #4060
